Category.create({name: 'Baguettes y ensaladas'})
Category.create({name: 'Postres'})
Category.create({name: 'Desayunos'})
Category.create({name: 'Botanas y golosinas'})
Category.create({name: 'Antojitos Mexicanos'})
Category.create({name: 'Pizzerías'})
Category.create({name: 'Taquerías'})
Category.create({name: 'Restaurant bar'})
Category.create({name: 'Loncherías'})
Category.create({name: 'Pollos'})
Category.create({name: 'Carnes'})
Category.create({name: 'Mariscos'})
Category.create({name: 'Birria y barbacoa'})
Category.create({name: 'Dogos y hamburguesas'})
Category.create({name: 'Comida oriental'})
Category.create({name: 'Cafe restaurant'})
Category.create({name: 'Cocina economica'})