Category.create({name: 'Baguettes y ensaladas', image: 'ensalada.jpg'})
Category.create({name: 'Postres', image: 'postres.jpg'})
Category.create({name: 'Desayunos', image: 'desayuno.jpg'})
Category.create({name: 'Botanas y golosinas', image: 'botanaygolosina.jpg' })
Category.create({name: 'Antojitos Mexicanos', image: 'antojitosmexicanos.jpg'})
Category.create({name: 'Pizzerías', image: 'pizzeria.jpg'})
Category.create({name: 'Taquerías', image: 'taqueria.jpg'})
Category.create({name: 'Restaurant bar', image: 'cocteleria.jpg'})
Category.create({name: 'Loncherías', image: 'loncheria.jpg'})
Category.create({name: 'Pollos', image: 'pollos.jpg'})
Category.create({name: 'Carnes', image: 'carnes.jpg'})
Category.create({name: 'Mariscos', image: 'mariscos.jpg'})
Category.create({name: 'Birria y barbacoa', image: 'birria.jpg'})
Category.create({name: 'Dogos y hamburguesas', image: 'dogoyhamburguesa.jpg'})
Category.create({name: 'Comida oriental', image: 'oriental.jpg'})
Category.create({name: 'Cafe restaurant', image: 'cafe.jpg'})
Category.create({name: 'Cocina economica', image: 'economica.jpg'})


Role.create({name: 'Cliente', description: 'Cliente comprador'})
Role.create({name: 'Administrador', description: 'Administrador general del sistema'})
Role.create({name: 'Restaurantero', description: 'Propietario y administrador de un restaurant'})
